add test cases for stage 2: Zicsr, exceptions and interrupts

diff --git a/tests/harness_tests/run_output_diff b/tests/harness_tests/run_output_diff
--- a/tests/harness_tests/run_output_diff
+++ b/tests/harness_tests/run_output_diff
@@ -1,17 +1,30 @@
-#!/bin/bash
+#!/bin/zsh
 RED='\033[0;31m'
 GREEN='\033[0;32m'
 NC='\033[0m' # No Color
 
-for i in *.log; do
-  if [[ $i != *-v.log && $i != sim.log ]]; then
-    OUT=$(diff --strip-trailing-cr $i expected/$i)
-    ret=$?
-    if [ "$OUT" != "" ]; then
-      printf "\n${RED}${i}${NC}\n"
-      echo "$OUT"
-    elif [ $ret -eq 0 ]; then
-      printf "\n${GREEN}${i}${NC}\n"
+test_cases=()
+
+for file in expected/*; do
+  if [[ -f "$file" ]]; then
+    base="$(basename "$file" | rev | cut -d. -f2- | rev)"
+    if [[ "$base" != *"-c" && "$base" != *"-v" ]]; then
+      test_cases+=("$base")
     fi
   fi
+done
+
+for i in "${test_cases[@]}"; do
+
+  OUT=$(diff --strip-trailing-cr ${i}.log expected/${i}.log)
+  ret=$?
+  if [ "$OUT" != "" ]; then
+    printf "\n${RED}${i}${NC}\n"
+    echo "$OUT"
+  elif [ $ret -eq 0 ]; then
+    printf "\n${GREEN}${i}${NC}\n"
+  else
+    printf "\n${RED}Missing: ${i}${NC}\n"
+  fi
+  
 done
